### PR TITLE
lots of numerics improvements

### PR DESCRIPTION
**Pull request by oscardssmith**
the main ones are `sqrt(sqrt(x))` instead of `x^.25` and `cispi(x)` instead of `exp(im*pi*x). I also started converting `abs` to `abs2` which is noticeably faster for complex, but I think I've missed a few.

### CODE REVIEW

**Comment by gbaraldi** [comment]
I believe `modulo` isn't equivalent to `mod` but to `rem`

**Comment by stla** [comment]
Yes, `modulo` is `rem`, thanks.

I've manually done the changes, because of conflicts.

I don't believe in the accuracy of `cispi`: I had to remove it, because one of my unit tests, a comparison with an exact value, is failing with `cispi`.

**Comment by stla** [comment]
Look:

```julia
julia> cispi(1im)
0.04321391826377052 + 0.0im

julia> exp(-pi)
0.04321391826377226
```

The second one is closer to Wolfram:

`0.04321391826377224977...`

**Comment by oscardssmith** [comment]
Oh, that's surprisingly inaccurate That shouldn't be happening.

**Comment by simonp0420** [comment]
The inaccuracy in `cispi` has been fixed, along with a 2x speedup in [this](https://github.com/JuliaLang/julia/pull/45945) PR

**Pull request closed without merging**
