### PR TITLE
Multiprecision tests for the Jacoby theta functions

### PR DESCRIPTION
**Pull request by kagalenko-m-b**
To begin addressing issue #11 I propose tests in this PR. Perhaps, the maintainers can make them stop failing?

### CODE REVIEW

**Comment by simonp0420** [comment]
it'll be at least a few weeks until I will have any time to help out with this.

**Comment by kagalenko-m-b** [comment]
I've made a few changes to the functions' source, so most multiprecision tests pass successfully now.

**Comment by stla** [comment]
Thanks @kagalenko-m-b ! Sounds great. Will take a look soon. Did you remove some tests? I quickly looked at the modified file and I had the impression that the test related to `jtheta1dash` has been removed.

**Comment by kagalenko-m-b** [comment]
>  I quickly looked at the modified file and I had the impression that the test related to `jtheta1dash` has been removed.

No, in fact, this is one of the failing tests and I can't understand why.

**Comment by simonp0420** [comment]
All tests now pass.  I've commented on the changes at https://github.com/kagalenko-m-b/EllipticFunctions.jl

**Comment by kagalenko-m-b** [comment]
Looks like the needed fix to `jtheta1dash()` has been pretty obvious, plus a typo while copying from Mathematica.  Thanks.

**Review by stla — APPROVED** [review]
looks ok

**Comment by kagalenko-m-b** [comment]
Great, thanks.

**Pull request merged**
