### PR TITLE
Fix nome tests

### PR DESCRIPTION
**Pull request by simonp0420**
Most of the problems were in the tests themselves, but there were also a couple of problems in the code.

### CODE REVIEW

**Comment by stla** [comment]
Thanks!!

**Comment by kagalenko-m-b** [comment]
Maybe, it's time to make this a registered package?

**Comment by stla** [comment]
Thanks both. My Linux laptop is broken. Now I only have an old laptop with Windows 7 and my work laptop with Windows 10. Will try to install Julia portable.

**Comment by simonp0420** [comment]
Sorry to hear about your hardware troubles.

**Pull request merged**
